# RandevuRezervasyonSistemi/docker-compose.yml 

services:
  db:
    image: postgres:15-alpine
    container_name: randevu_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-randevuuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-RandevuDB2025SecurePass}
      POSTGRES_DB: ${POSTGRES_DB:-randevuplatformu_db}
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"

  api:
    container_name: randevu_api
    build:
      context: ./backend
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-randevuuser}:${POSTGRES_PASSWORD:-RandevuDB2025SecurePass}@db:5432/${POSTGRES_DB:-randevuplatformu_db}
    depends_on:
      - db
    
  nginx:
    image: nginx:1.25-alpine
    container_name: randevu_nginx
    ports:
      - "80:80"
    volumes:
      # DÜZELTME: Yol 'build' yerine 'dist' olarak değiştirildi.
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

volumes:
  postgres_data: