"""Add start_date and end_date to pricing_rules

Revision ID: 90eb8f568b04
Revises: 265bd9f88a3e
Create Date: 2025-07-10 10:32:00.581791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90eb8f568b04'
down_revision: Union[str, Sequence[str], None] = '265bd9f88a3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
