# backend/alembic/versions/a055b5b706a0_.... .py dosyasının tam hali

"""Resource tablosuna yeni rezervasyon kuralları eklendi

Revision ID: a055b5b706a0
Revises: 8b0d8190de9d
Create Date: 2025-07-25 13:45:00.123456 # Bu tarih sizde farklı olabilir

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a055b5b706a0'
down_revision: Union[str, Sequence[str], None] = '8b0d8190de9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # YENİ EKLENDİ: Önce Enum tipini veritabanında oluşturuyoruz.
    booking_type_enum = sa.Enum('SLOT_BASED', 'DURATION_BASED', name='bookingtype')
    booking_type_enum.create(op.get_bind())
    
    # DÜZELTİLDİ: server_default'u kaldırıp, sa.Enum içine name parametresini ekliyoruz.
    op.add_column('resources', sa.Column('booking_type', sa.Enum('SLOT_BASED', 'DURATION_BASED', name='bookingtype'), nullable=False, server_default='SLOT_BASED'))
    op.add_column('resources', sa.Column('max_bookings_per_day', sa.Integer(), nullable=True))
    op.add_column('resources', sa.Column('max_bookings_per_customer', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'max_bookings_per_customer')
    op.drop_column('resources', 'max_bookings_per_day')
    op.drop_column('resources', 'booking_type')
    
    # YENİ EKLENDİ: Sütun silindikten sonra Enum tipini de veritabanından siliyoruz.
    booking_type_enum = sa.Enum('SLOT_BASED', 'DURATION_BASED', name='bookingtype')
    booking_type_enum.drop(op.get_bind())
    # ### end Alembic commands ###